grub:
  theme: tela
  icon: color
  screen: 1080p
packages:
  install:
    - bat
    - brave-bin
    - chezmoi
    - discord
    - docker
    - docker-compose
    - eza
    - fish
    - helix
    - man
    - meson
    - ninja
    - nodejs
    - npm
    - tmux
    - ttf-iosevka-nerd
    - ttf-noto-nerd
    - unzip
    - visual-studio-code-bin
    - zip
    - zoxide
  uninstall:
    - gnome-software
