grub:
  theme: tela
  icon: color
  screen: 1080p
gnome:
  centerNewWindows: true
  buttonLayout: appmenu:minimize,maximize,close
  fonts:
    default: NotoSans Nerd Font Regular 11
    document: NotoSans Nerd Font Regular 11
    monospace: Iosevka Nerd Font Propo Medium 12
    titlebar: NotoSans Nerd Font Semi-Bold 11
packages:
  install:
    - bat
    - bottom
    - brave-bin
    - chezmoi
    - discord
    - docker
    - docker-compose
    - eza
    - fish
    - helix
    - lazygit
    - man
    - neovim
    - nodejs
    - npm
    - python
    - ripgrep
    - tmux
    - tree-sitter
    - tree-sitter-cli
    - ttf-iosevka-nerd
    - ttf-noto-nerd
    - unzip
    - visual-studio-code-bin
    - wl-clipboard
    - xclip
    - xsel
    - zip
    - zoxide
  uninstall:
    - gnome-software
