.yay:
  type: git-repo
  url: https://aur.archlinux.org/yay-bin.git
.tmux/plugins/tpm:
  type: git-repo
  url: https://github.com/tmux-plugins/tpm
.grub2-themes:
  type: git-repo
  url: https://github.com/vinceliuice/grub2-themes
.fisher.fish:
  type: file
  url: https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish
.config/nvim:
  type: git-repo
  url: https://github.com/pepetrov0/nvchad
